# Amazon-Style E-Commerce Sales Analytics
## 01 — Data Cleaning

### Objective

The objective of this notebook is to inspect, validate, and clean the Amazon-style e-commerce dataset before performing exploratory data analysis and business analysis.

The dataset contains order, customer, product, pricing, discount, payment, geographic, and seller information.

### Key Data Cleaning Tasks

- Inspect dataset structure and dimensions
- Identify missing values
- Identify duplicate records
- Validate data types
- Check categorical consistency
- Validate numerical values
- Validate dates
- Check financial calculations
- Identify potential data-quality issues
- Create a clean dataset for further analysis

In [1]:
### Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
file_path = "C:/Users/HP/OneDrive/Desktop/Projects/Amazon E-Commerce Sales Performance & Customer Analytics/Data/Amazon.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 100000
Columns: 20

In [5]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [6]:
df.tail()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
99995,ORD0099996,2023-03-07,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,0.00,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,2021-11-24,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,0.00,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,2023-04-29,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,0.00,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,2021-11-01,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,0.00,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,2021-12-04,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  str
 1   OrderDate      100000 non-null  str
 2   CustomerID     100000 non-null  str
 3   CustomerName   100000 non-null  str
 4   ProductID      100000 non-null  str
 5   ProductName    100000 non-null  str
 6   Category       100000 non-null  str
 7   Brand          100000 non-null  str
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       100000 non-null  float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    100000 non-null  float64
 14  PaymentMethod  100000 non-null  str
 15  OrderStatus    100000 non-null  str
 16  City           100000 non-null  str
 17  State          100000 non-null  str
 18  Country        100000 non-null  str
 19  SellerID       100000 non-null  str
dtypes: float64(5), int64(1), str(14)
memory usage: 15.3 MB

In [8]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
OrderID,100000,100000,ORD0000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OrderDate,100000,1825,2022-04-28,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerID,100000,43233,CUST023748,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerName,100000,200,Karan Joshi,556,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ProductID,100000,50,P00019,2098,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ProductName,100000,50,LED Desk Lamp,2098,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,100000,6,Electronics,16853,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brand,100000,10,ReadMore,10204,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,100000.0,NaN,NaN,NaN,3.0014,1.413548,1.0,2.0,3.0,4.0,5.0
UnitPrice,100000.0,NaN,NaN,NaN,302.905748,171.840797,5.0,154.19,303.07,451.5,599.99
Discount,100000.0,NaN,NaN,NaN,0.074226,0.082583,0.0,0.0,0.05,0.1,0.3
Tax,100000.0,NaN,NaN,NaN,68.468902,74.13118,0.0,15.92,45.25,96.06,538.46
ShippingCost,100000.0,NaN,NaN,NaN,7.40666,4.324057,0.0,3.68,7.3,11.15,15.0
TotalAmount,100000.0,NaN,NaN,NaN,918.256479,724.508332,4.27,340.89,714.315,1349.765,3534.98
PaymentMethod,100000,6,Credit Card,35038,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OrderStatus,100000,5,Delivered,74628,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,100000,20,Charlotte,5110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,100000,13,TX,24896,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,100000,5,United States,70058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SellerID,100000,1999,SELL01099,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.columns.tolist()

['OrderID',
 'OrderDate',
 'CustomerID',
 'CustomerName',
 'ProductID',
 'ProductName',
 'Category',
 'Brand',
 'Quantity',
 'UnitPrice',
 'Discount',
 'Tax',
 'ShippingCost',
 'TotalAmount',
 'PaymentMethod',
 'OrderStatus',
 'City',
 'State',
 'Country',
 'SellerID']

In [10]:
df.columns.tolist()

['OrderID',
 'OrderDate',
 'CustomerID',
 'CustomerName',
 'ProductID',
 'ProductName',
 'Category',
 'Brand',
 'Quantity',
 'UnitPrice',
 'Discount',
 'Tax',
 'ShippingCost',
 'TotalAmount',
 'PaymentMethod',
 'OrderStatus',
 'City',
 'State',
 'Country',
 'SellerID']

In [11]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID', 'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount', 'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus', 'City', 'State', 'Country', 'SellerID']

In [12]:
missing_values = df.isnull().sum()

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": missing_percentage
})

missing_summary.sort_values(
    by="Missing Values",
    ascending=False
)

               Missing Values  Missing Percentage
OrderID                     0                 0.0
OrderDate                   0                 0.0
CustomerID                  0                 0.0
CustomerName                0                 0.0
ProductID                   0                 0.0
ProductName                 0                 0.0
Category                    0                 0.0
Brand                       0                 0.0
Quantity                    0                 0.0
UnitPrice                   0                 0.0
Discount                    0                 0.0
Tax                         0                 0.0
ShippingCost                0                 0.0
TotalAmount                 0                 0.0
PaymentMethod               0                 0.0
OrderStatus                 0                 0.0
City                        0                 0.0
State                       0                 0.0
Country                     0                 0.0
SellerID                    0                 0.0

In [13]:
print(df.columns.tolist())

['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID', 'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount', 'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus', 'City', 'State', 'Country', 'SellerID']

In [14]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [15]:
duplicate_order_ids = df["OrderID"].duplicated().sum()

print("Duplicate OrderIDs:", duplicate_order_ids)

Duplicate OrderIDs: 0

In [16]:
df.dtypes

OrderID              str
OrderDate            str
CustomerID           str
CustomerName         str
ProductID            str
ProductName          str
Category             str
Brand                str
Quantity           int64
UnitPrice        float64
Discount         float64
Tax              float64
ShippingCost     float64
TotalAmount      float64
PaymentMethod        str
OrderStatus          str
City                 str
State                str
Country              str
SellerID             str
dtype: object

In [17]:
df["OrderDate"] = pd.to_datetime(
    df["OrderDate"],
    errors="coerce"
)

In [18]:
df["OrderDate"].dtype

dtype('<M8[us]')

In [19]:
print("Minimum Order Date:", df["OrderDate"].min())
print("Maximum Order Date:", df["OrderDate"].max())

Minimum Order Date: 2020-01-01 00:00:00
Maximum Order Date: 2024-12-29 00:00:00

In [20]:
invalid_dates = df["OrderDate"].isna().sum()

print("Invalid dates:", invalid_dates)

Invalid dates: 0

In [21]:
print("Unique years:", sorted(df["OrderDate"].dt.year.dropna().unique()))

Unique years: [np.int32(2020), np.int32(2021), np.int32(2022), np.int32(2023), np.int32(2024)]

In [22]:
numeric_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns

numeric_columns

Index(['Quantity', 'UnitPrice', 'Discount', 'Tax', 'ShippingCost',
       'TotalAmount'],
      dtype='str')

In [23]:
df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity,100000.0,3.001400,1.413548,1.00,2.00,3.000,4.000,5.00
UnitPrice,100000.0,302.905748,171.840797,5.00,154.19,303.070,451.500,599.99
Discount,100000.0,0.074226,0.082583,0.00,0.00,0.050,0.100,0.30
Tax,100000.0,68.468902,74.131180,0.00,15.92,45.250,96.060,538.46
ShippingCost,100000.0,7.406660,4.324057,0.00,3.68,7.300,11.150,15.00
TotalAmount,100000.0,918.256479,724.508332,4.27,340.89,714.315,1349.765,3534.98

In [24]:
negative_values = {}

for column in numeric_columns:
    count = (df[column] < 0).sum()
    negative_values[column] = count

negative_values

{'Quantity': np.int64(0),
 'UnitPrice': np.int64(0),
 'Discount': np.int64(0),
 'Tax': np.int64(0),
 'ShippingCost': np.int64(0),
 'TotalAmount': np.int64(0)}

In [25]:
print("Minimum Quantity:", df["Quantity"].min())
print("Maximum Quantity:", df["Quantity"].max())

print(
    "Zero Quantity:",
    (df["Quantity"] == 0).sum()
)

print(
    "Negative Quantity:",
    (df["Quantity"] < 0).sum()
)

Minimum Quantity: 1
Maximum Quantity: 5
Zero Quantity: 0
Negative Quantity: 0

In [26]:
price_columns = [
    "UnitPrice",
    "Discount",
    "Tax",
    "ShippingCost",
    "TotalAmount"
]

df[price_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
UnitPrice,100000.0,302.905748,171.840797,5.00,154.19,303.070,451.500,599.99
Discount,100000.0,0.074226,0.082583,0.00,0.00,0.050,0.100,0.30
Tax,100000.0,68.468902,74.131180,0.00,15.92,45.250,96.060,538.46
ShippingCost,100000.0,7.406660,4.324057,0.00,3.68,7.300,11.150,15.00
TotalAmount,100000.0,918.256479,724.508332,4.27,340.89,714.315,1349.765,3534.98

In [27]:
for column in price_columns:
    print(
        column,
        "negative values:",
        (df[column] < 0).sum()
    )

UnitPrice negative values: 0
Discount negative values: 0
Tax negative values: 0
ShippingCost negative values: 0
TotalAmount negative values: 0

In [28]:
print("Minimum discount:", df["Discount"].min())
print("Maximum discount:", df["Discount"].max())

Minimum discount: 0.0
Maximum discount: 0.3

In [29]:
df["Discount"].value_counts().sort_index().head(20)

Discount
0.00    40246
0.05    19889
0.10    14910
0.15    10041
0.20     7939
0.25     4986
0.30     1989
Name: count, dtype: int64

In [30]:
df["CalculatedTotal"] = (
    df["Quantity"] *
    df["UnitPrice"] *
    (1 - df["Discount"]) +
    df["Tax"] +
    df["ShippingCost"]
)

In [31]:
df["AmountDifference"] = (
    df["TotalAmount"] -
    df["CalculatedTotal"]
)

df["AmountDifference"].describe()

count    1.000000e+05
mean    -2.053500e-05
std      2.229484e-03
min     -5.000000e-03
25%     -4.547474e-13
50%      0.000000e+00
75%      2.273737e-13
max      5.000000e-03
Name: AmountDifference, dtype: float64

In [32]:
df["AmountDifference"].abs().max()

np.float64(0.005000000000109139)

In [33]:
df.loc[
    df["AmountDifference"].abs().nlargest(10).index,
    [
        "OrderID",
        "Quantity",
        "UnitPrice",
        "Discount",
        "Tax",
        "ShippingCost",
        "TotalAmount",
        "CalculatedTotal",
        "AmountDifference"
    ]
]

,OrderID,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,CalculatedTotal,AmountDifference
87,ORD0000088,5,456.58,0.15,155.24,7.48,2103.18,2103.185,-0.005
154,ORD0000155,3,414.46,0.25,111.90,4.69,1049.12,1049.125,-0.005
167,ORD0000168,5,232.62,0.05,88.40,9.35,1202.70,1202.695,0.005
229,ORD0000230,5,493.81,0.30,138.27,14.70,1881.30,1881.305,-0.005
611,ORD0000612,5,367.29,0.10,132.22,2.54,1787.56,1787.565,-0.005
627,ORD0000628,3,513.55,0.10,166.39,1.44,1554.42,1554.415,0.005
679,ORD0000680,5,373.90,0.15,79.45,7.32,1675.84,1675.845,-0.005
737,ORD0000738,5,587.98,0.25,396.89,14.43,2616.24,2616.245,-0.005
879,ORD0000880,5,510.26,0.05,121.19,1.85,2546.78,2546.775,0.005
930,ORD0000931,5,549.70,0.05,130.55,4.19,2745.82,2745.815,0.005

In [34]:
categorical_columns = df.select_dtypes(
    include=["object"]
).columns

categorical_columns

C:\Users\Hp\AppData\Local\Temp\ipykernel_12856\2213581602.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

Index(['OrderID', 'CustomerID', 'CustomerName', 'ProductID', 'ProductName',
       'Category', 'Brand', 'PaymentMethod', 'OrderStatus', 'City', 'State',
       'Country', 'SellerID'],
      dtype='str')

In [35]:
for column in categorical_columns:
    print("\n" + "=" * 60)
    print(column)
    print("Unique values:", df[column].nunique())
    print(df[column].value_counts().head(20))

============================================================
OrderID
Unique values: 100000
OrderID
ORD0000001    1
ORD0000002    1
ORD0000003    1
ORD0000004    1
ORD0000005    1
ORD0000006    1
ORD0000007    1
ORD0000008    1
ORD0000009    1
ORD0000010    1
ORD0000011    1
ORD0000012    1
ORD0000013    1
ORD0000014    1
ORD0000015    1
ORD0000016    1
ORD0000017    1
ORD0000018    1
ORD0000019    1
ORD0000020    1
Name: count, dtype: int64

============================================================
CustomerID
Unique values: 43233
CustomerID
CUST023748    10
CUST037103    10
CUST036736     9
CUST003244     9
CUST009614     9
CUST005654     9
CUST029942     9
CUST042938     9
CUST034288     9
CUST031337     9
CUST043080     9
CUST048737     9
CUST029921     9
CUST012611     9
CUST001153     9
CUST005934     8
CUST010510     8
CUST034569     8
CUST022597     8
CUST037882     8
Name: count, dtype: int64

============================================================
CustomerName
Unique values: 200
CustomerName
Karan Joshi      556
Arjun Kumar      553
Pooja Kapoor     552
Rohit Gupta      547
Vihaan Singh     544
Aditya Mehta     543
Vihaan Mehta     541
Pooja Singh      538
Neha Kumar       538
Aditya Joshi     537
Aman Reddy       536
Sunita Joshi     535
Karan Singh      534
Neha Joshi       534
Kabir Joshi      532
Vihaan Sharma    530
Mohit Mehta      530
Vikas Kapoor     528
Neha Mehta       528
Sunita Kumar     528
Name: count, dtype: int64

============================================================
ProductID
Unique values: 50
ProductID
P00019    2098
P00022    2088
P00023    2058
P00037    2054
P00017    2054
P00024    2041
P00047    2039
P00032    2039
P00036    2036
P00040    2034
P00007    2034
P00048    2034
P00012    2031
P00009    2030
P00014    2026
P00034    2026
P00013    2024
P00020    2018
P00018    2017
P00015    2016
Name: count, dtype: int64

============================================================
ProductName
Unique values: 50
ProductName
LED Desk Lamp                  2098
Water Bottle                   2088
Cookware Set                   2058
Router                         2054
Electric Kettle                2054
Yoga Mat                       2041
Memory Card 128GB              2039
Board Game                     2039
Smart Light Bulb               2036
Microphone                     2034
Mechanical Keyboard            2034
Wireless Charger               2034
Noise Cancelling Headphones    2031
Portable SSD 1TB               2030
Drone Mini                     2026
Desk Organizer                 2026
Action Camera                  2024
Office Chair                   2018
Vacuum Cleaner                 2017
Instant Pot                    2016
Name: count, dtype: int64

============================================================
Category
Unique values: 6
Category
Electronics          16853
Sports & Outdoors    16804
Books                16752
Home & Kitchen       16610
Toys & Games         16542
Clothing             16439
Name: count, dtype: int64

============================================================
Brand
Unique values: 10
Brand
ReadMore      10204
FitLife       10147
CoreTech      10127
KiddoFun      10077
Zenith         9990
NexPro         9962
Apex           9937
BrightLux      9907
UrbanStyle     9854
HomeEase       9795
Name: count, dtype: int64

============================================================
PaymentMethod
Unique values: 6
PaymentMethod
Credit Card         35038
Debit Card          20024
UPI                 15066
Amazon Pay          15017
Net Banking          9927
Cash on Delivery     4928
Name: count, dtype: int64

============================================================
OrderStatus
Unique values: 5
OrderStatus
Delivered    74628
Shipped      15192
Pending       4103
Returned      3049
Cancelled     3028
Name: count, dtype: int64

============================================================
City
Unique values: 20
City
Charlotte        5110
Jacksonville     5107
San Jose         5107
Dallas           5105
Los Angeles      5058
Austin           5043
Seattle          5039
Washington       5021
Columbus         5021
Chicago          5020
Philadelphia     5014
Denver           4991
Indianapolis     4970
New York         4949
Phoenix          4941
Fort Worth       4934
San Francisco    4930
San Antonio      4913
Houston          4901
San Diego        4826
Name: count, dtype: int64

============================================================
State
Unique values: 13
State
TX    24896
CA    19921
NC     5110
FL     5107
WA     5039
DC     5021
OH     5021
IL     5020
PA     5014
CO     4991
IN     4970
NY     4949
AZ     4941
Name: count, dtype: int64

============================================================
Country
Unique values: 5
Country
United States     70058
India             15051
Canada             5818
United Kingdom     4943
Australia          4130
Name: count, dtype: int64

============================================================
SellerID
Unique values: 1999
SellerID
SELL01099    78
SELL01335    71
SELL00792    71
SELL00536    70
SELL01447    70
SELL01584    69
SELL00709    69
SELL00876    69
SELL00812    68
SELL01241    68
SELL00264    68
SELL00178    68
SELL01368    68
SELL01122    67
SELL00806    67
SELL00046    67
SELL00347    67
SELL00004    67
SELL01653    67
SELL01823    67
Name: count, dtype: int64

In [36]:
df["OrderStatus"].value_counts()

OrderStatus
Delivered    74628
Shipped      15192
Pending       4103
Returned      3049
Cancelled     3028
Name: count, dtype: int64

In [37]:
df["OrderStatus"].value_counts(normalize=True) * 100

OrderStatus
Delivered    74.628
Shipped      15.192
Pending       4.103
Returned      3.049
Cancelled     3.028
Name: proportion, dtype: float64

In [38]:
print("Categories:")
print(df["Category"].unique())

print("\nNumber of categories:", df["Category"].nunique())

print("\nBrands:")
print(df["Brand"].unique())

print("\nNumber of brands:", df["Brand"].nunique())

Categories:
<StringArray>
[            'Books',    'Home & Kitchen',          'Clothing',
      'Toys & Games', 'Sports & Outdoors',       'Electronics']
Length: 6, dtype: str

Number of categories: 6

Brands:
<StringArray>
[ 'BrightLux', 'UrbanStyle',     'Zenith',   'KiddoFun',   'ReadMore',
       'Apex',   'HomeEase',    'FitLife',   'CoreTech',     'NexPro']
Length: 10, dtype: str

Number of brands: 10

In [39]:
df["PaymentMethod"].value_counts()

PaymentMethod
Credit Card         35038
Debit Card          20024
UPI                 15066
Amazon Pay          15017
Net Banking          9927
Cash on Delivery     4928
Name: count, dtype: int64

In [41]:
print("Countries:", df["Country"].unique())
print("\nStates:", df["State"].unique())

Countries: <StringArray>
['India', 'United States', 'Canada', 'Australia', 'United Kingdom']
Length: 5, dtype: str

States: <StringArray>
['DC', 'TX', 'NC', 'CA', 'IL', 'CO', 'FL', 'NY', 'WA', 'IN', 'PA', 'AZ', 'OH']
Length: 13, dtype: str

In [43]:
country_state_check = (
    df.groupby("Country")["State"]
    .nunique()
    .sort_values(ascending=False)
)

country_state_check

Country
Australia         13
Canada            13
India             13
United Kingdom    13
United States     13
Name: State, dtype: int64

In [44]:
pd.crosstab(
    df["Country"],
    df["State"]
)

State,AZ,CA,CO,DC,FL,IL,IN,NC,NY,OH,PA,TX,WA
Country,,,,,,,,,,,,,
Australia,179,782,198,214,214,219,209,209,210,214,206,1044,232
Canada,312,1120,296,276,279,278,272,309,296,272,312,1500,296
India,697,3041,776,702,756,778,796,743,758,767,706,3797,734
United Kingdom,250,964,259,269,264,238,224,243,244,247,247,1221,273
United States,3503,14014,3462,3560,3594,3507,3469,3606,3441,3521,3543,17334,3504

In [45]:
id_columns = [
    "OrderID",
    "CustomerID",
    "ProductID",
    "SellerID"
]

categorical_analysis_columns = [
    col for col in categorical_columns
    if col not in id_columns
]

for column in categorical_analysis_columns:
    print("\n" + "=" * 60)
    print(column)
    print("Unique values:", df[column].nunique())
    print(df[column].value_counts().head(15))

============================================================
CustomerName
Unique values: 200
CustomerName
Karan Joshi     556
Arjun Kumar     553
Pooja Kapoor    552
Rohit Gupta     547
Vihaan Singh    544
Aditya Mehta    543
Vihaan Mehta    541
Pooja Singh     538
Neha Kumar      538
Aditya Joshi    537
Aman Reddy      536
Sunita Joshi    535
Karan Singh     534
Neha Joshi      534
Kabir Joshi     532
Name: count, dtype: int64

============================================================
ProductName
Unique values: 50
ProductName
LED Desk Lamp                  2098
Water Bottle                   2088
Cookware Set                   2058
Router                         2054
Electric Kettle                2054
Yoga Mat                       2041
Memory Card 128GB              2039
Board Game                     2039
Smart Light Bulb               2036
Microphone                     2034
Mechanical Keyboard            2034
Wireless Charger               2034
Noise Cancelling Headphones    2031
Portable SSD 1TB               2030
Drone Mini                     2026
Name: count, dtype: int64

============================================================
Category
Unique values: 6
Category
Electronics          16853
Sports & Outdoors    16804
Books                16752
Home & Kitchen       16610
Toys & Games         16542
Clothing             16439
Name: count, dtype: int64

============================================================
Brand
Unique values: 10
Brand
ReadMore      10204
FitLife       10147
CoreTech      10127
KiddoFun      10077
Zenith         9990
NexPro         9962
Apex           9937
BrightLux      9907
UrbanStyle     9854
HomeEase       9795
Name: count, dtype: int64

============================================================
PaymentMethod
Unique values: 6
PaymentMethod
Credit Card         35038
Debit Card          20024
UPI                 15066
Amazon Pay          15017
Net Banking          9927
Cash on Delivery     4928
Name: count, dtype: int64

============================================================
OrderStatus
Unique values: 5
OrderStatus
Delivered    74628
Shipped      15192
Pending       4103
Returned      3049
Cancelled     3028
Name: count, dtype: int64

============================================================
City
Unique values: 20
City
Charlotte       5110
Jacksonville    5107
San Jose        5107
Dallas          5105
Los Angeles     5058
Austin          5043
Seattle         5039
Washington      5021
Columbus        5021
Chicago         5020
Philadelphia    5014
Denver          4991
Indianapolis    4970
New York        4949
Phoenix         4941
Name: count, dtype: int64

============================================================
State
Unique values: 13
State
TX    24896
CA    19921
NC     5110
FL     5107
WA     5039
DC     5021
OH     5021
IL     5020
PA     5014
CO     4991
IN     4970
NY     4949
AZ     4941
Name: count, dtype: int64

============================================================
Country
Unique values: 5
Country
United States     70058
India             15051
Canada             5818
United Kingdom     4943
Australia          4130
Name: count, dtype: int64

In [46]:
print("OrderID format examples:")
print(df["OrderID"].head())

print("\nCustomerID format examples:")
print(df["CustomerID"].head())

print("\nProductID format examples:")
print(df["ProductID"].head())

print("\nSellerID format examples:")
print(df["SellerID"].head())

OrderID format examples:
0    ORD0000001
1    ORD0000002
2    ORD0000003
3    ORD0000004
4    ORD0000005
Name: OrderID, dtype: str

CustomerID format examples:
0    CUST001504
1    CUST000178
2    CUST047516
3    CUST030059
4    CUST048677
Name: CustomerID, dtype: str

ProductID format examples:
0    P00014
1    P00040
2    P00044
3    P00041
4    P00029
Name: ProductID, dtype: str

SellerID format examples:
0    SELL01967
1    SELL01298
2    SELL00908
3    SELL01164
4    SELL01411
Name: SellerID, dtype: str

In [47]:
id_columns = [
    "OrderID",
    "CustomerID",
    "ProductID",
    "SellerID"
]

for column in id_columns:
    print(
        column,
        "missing:", df[column].isna().sum(),
        "| unique:", df[column].nunique()
    )

OrderID missing: 0 | unique: 100000
CustomerID missing: 0 | unique: 43233
ProductID missing: 0 | unique: 50
SellerID missing: 0 | unique: 1999

In [48]:
text_columns = df.select_dtypes(include="object").columns

for column in text_columns:
    leading_trailing_spaces = (
        df[column].astype(str) != df[column].astype(str).str.strip()
    ).sum()

    print(
        f"{column}: {leading_trailing_spaces} values "
        "with leading/trailing spaces"
    )

C:\Users\Hp\AppData\Local\Temp\ipykernel_12856\543305917.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

OrderID: 0 values with leading/trailing spaces
CustomerID: 0 values with leading/trailing spaces
CustomerName: 0 values with leading/trailing spaces
ProductID: 0 values with leading/trailing spaces
ProductName: 0 values with leading/trailing spaces
Category: 0 values with leading/trailing spaces
Brand: 0 values with leading/trailing spaces
PaymentMethod: 0 values with leading/trailing spaces
OrderStatus: 0 values with leading/trailing spaces
City: 0 values with leading/trailing spaces
State: 0 values with leading/trailing spaces
Country: 0 values with leading/trailing spaces
SellerID: 0 values with leading/trailing spaces

In [49]:
for column in text_columns:
    df[column] = df[column].str.strip()

In [50]:
important_categories = [
    "Category",
    "Brand",
    "PaymentMethod",
    "OrderStatus",
    "Country"
]

for column in important_categories:
    print(f"\n{column}")
    print(df[column].value_counts())

Category
Category
Electronics          16853
Sports & Outdoors    16804
Books                16752
Home & Kitchen       16610
Toys & Games         16542
Clothing             16439
Name: count, dtype: int64

Brand
Brand
ReadMore      10204
FitLife       10147
CoreTech      10127
KiddoFun      10077
Zenith         9990
NexPro         9962
Apex           9937
BrightLux      9907
UrbanStyle     9854
HomeEase       9795
Name: count, dtype: int64

PaymentMethod
PaymentMethod
Credit Card         35038
Debit Card          20024
UPI                 15066
Amazon Pay          15017
Net Banking          9927
Cash on Delivery     4928
Name: count, dtype: int64

OrderStatus
OrderStatus
Delivered    74628
Shipped      15192
Pending       4103
Returned      3049
Cancelled     3028
Name: count, dtype: int64

Country
Country
United States     70058
India             15051
Canada             5818
United Kingdom     4943
Australia          4130
Name: count, dtype: int64

In [51]:
geo_check = (
    df.groupby("Country")["State"]
    .nunique()
    .sort_values(ascending=False)
)

geo_check

Country
Australia         13
Canada            13
India             13
United Kingdom    13
United States     13
Name: State, dtype: int64

In [53]:
geo_cross_tab = pd.crosstab(
    df["Country"],
    df["State"]
)

geo_cross_tab

State,AZ,CA,CO,DC,FL,IL,IN,NC,NY,OH,PA,TX,WA
Country,,,,,,,,,,,,,
Australia,179,782,198,214,214,219,209,209,210,214,206,1044,232
Canada,312,1120,296,276,279,278,272,309,296,272,312,1500,296
India,697,3041,776,702,756,778,796,743,758,767,706,3797,734
United Kingdom,250,964,259,269,264,238,224,243,244,247,247,1221,273
United States,3503,14014,3462,3560,3594,3507,3469,3606,3441,3521,3543,17334,3504

In [54]:
df[["City", "State", "Country"]].drop_duplicates().head(30)

             City State         Country
0      Washington    DC           India
1      Fort Worth    TX   United States
2          Austin    TX   United States
3       Charlotte    NC           India
4     San Antonio    TX          Canada
5     Los Angeles    CA   United States
6         Chicago    IL       Australia
7          Denver    CO           India
8      Washington    DC   United States
9         Houston    TX   United States
10   Jacksonville    FL       Australia
11      Charlotte    NC       Australia
12       New York    NY   United States
13        Seattle    WA   United States
14   Indianapolis    IN   United States
15   Jacksonville    FL   United States
16   Philadelphia    PA   United States
18        Phoenix    AZ   United States
19      San Diego    CA   United States
22        Phoenix    AZ          Canada
23         Dallas    TX   United States
25       Columbus    OH          Canada
26  San Francisco    CA   United States
27    San Antonio    TX  United Kingdom
28         Denver    CO   United States
30      Charlotte    NC  United Kingdom
31        Houston    TX           India
35       Columbus    OH  United Kingdom
40        Chicago    IL   United States
41    San Antonio    TX   United States

In [55]:
print("Discount below 0:",
      (df["Discount"] < 0).sum())

print("Discount above 1:",
      (df["Discount"] > 1).sum())

Discount below 0: 0
Discount above 1: 0

In [56]:
print("Quantity <= 0:",
      (df["Quantity"] <= 0).sum())

Quantity <= 0: 0

In [57]:
print("Tax < 0:",
      (df["Tax"] < 0).sum())

Tax < 0: 0

In [58]:
print("ShippingCost < 0:",
      (df["ShippingCost"] < 0).sum())

ShippingCost < 0: 0

In [59]:
quality_summary = pd.DataFrame({
    "Check": [
        "Total Rows",
        "Total Columns",
        "Missing Values",
        "Duplicate Rows",
        "Duplicate OrderIDs",
        "Invalid Dates",
        "Future Dates",
        "Negative Quantity",
        "Negative UnitPrice",
        "Negative Discount",
        "Negative Tax",
        "Negative ShippingCost"
    ],
    "Result": [
        len(df),
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df["OrderID"].duplicated().sum(),
        df["OrderDate"].isna().sum(),
        (df["OrderDate"] > pd.Timestamp.today()).sum(),
        (df["Quantity"] < 0).sum(),
        (df["UnitPrice"] < 0).sum(),
        (df["Discount"] < 0).sum(),
        (df["Tax"] < 0).sum(),
        (df["ShippingCost"] < 0).sum()
    ]
})

quality_summary

                    Check  Result
0              Total Rows  100000
1           Total Columns      22
2          Missing Values       0
3          Duplicate Rows       0
4      Duplicate OrderIDs       0
5           Invalid Dates       0
6            Future Dates       0
7       Negative Quantity       0
8      Negative UnitPrice       0
9       Negative Discount       0
10           Negative Tax       0
11  Negative ShippingCost       0

In [60]:
df.drop(
    columns=["CalculatedTotal", "AmountDifference"],
    inplace=True
)

In [61]:
df["Year"] = df["OrderDate"].dt.year
df["Month"] = df["OrderDate"].dt.month
df["MonthName"] = df["OrderDate"].dt.month_name()
df["Quarter"] = df["OrderDate"].dt.quarter
df["YearMonth"] = df["OrderDate"].dt.to_period("M").astype(str)

In [63]:
output_path = "C:/Users/HP/OneDrive/Desktop/Projects/Amazon E-Commerce Sales Performance & Customer Analytics/Data/Amazon_Cleaned.csv"

df.to_csv(
    output_path,
    index=False
)

print("Cleaned dataset saved successfully.")
print("Shape:", df.shape)

Cleaned dataset saved successfully.
Shape: (100000, 25)

## 18. Conclusion

The Amazon-style e-commerce dataset was systematically inspected and validated before exploratory analysis.

The data-cleaning process included:

- Dataset structure and dimensionality inspection
- Missing-value analysis
- Duplicate-record validation
- OrderID uniqueness validation
- Data-type validation
- Date validation
- Numerical-value validation
- Financial calculation validation
- Categorical consistency checks
- Geographic data-quality assessment
- Business-rule validation
- Date-based feature engineering

The validated dataset has been exported as `Amazon_Cleaned.csv` and will be used for the subsequent exploratory data analysis and SQL stages of the project.

Geographic fields will be interpreted carefully because the dataset is synthetic and may contain inconsistent Country, State, and City combinations.